config/routes.rb
Rails.application.routes.draw do
  resources :followers do |r|
    collection do
      get 'random'
      delete 'unfollow'

    end
  end
  resources :tweets
  get 'profile' => 'profile#index'
  patch 'profile' => 'profile#update'

  devise_for :users

   root 'home#index'

end

app/models/follower.rb
class Follower < ActiveRecord::Base
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
	belongs_to :user

	def as_json(options={}) 	
		super(methods: [:name, :gravatar])
		
	end

	def name
		user.display_name
		
	end

	def gravatar
		user.gravatar
	end

	def self.stream_for(current_user_id)
		joins(:user)
		.where(["users.id = :current_user_id or users.id in (
			select user_id from followers
			where followed_by = :current_user_id
			)", {current_user_id: current_user_id}])
		.order(created_at: :desc)
		.all
		
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def as_json(options={}) 	
	{id: id, name: display_name, gravatar: gravatar}   #forced serialized json
		
  end

  def display_name
  	first_name.present? ? "#{first_name} #{last_name}" : email
  end

  def name
  	first_name.present? ? "#{first_name} #{last_name}" : email
  end

  def gravatar
  		hash = Digest::MD5.hexdigest(email.downcase)
		"http://www.gravatar.com/avatar/#{hash}"
  end

  def self.who_to_follow(current_user_id)     # I DONT GET IT!!! REMEMBER TO CHECK THIS OUT!!!!
  	where(["id != :current_user_id and not exists (         
  		select 1 from followers
  		where user_id = users.id
  		and followed_by = :current_user_id)", {current_user_id: current_user_id }]).all
  	 #THIS LIST ALL RECORDS IN THE USERS TABLE EXCLUDING CURRENT USERS RECORDS AND EXCLUDING ALL USERS WHO
  	 #EXIST IN  THE LIST OF USERS THE CURRENT USER IS FOLLOWINNG
  	
  end

  def self.following(current_user_id)   # LIST OF USERS WHO THE CURRENT USER IS FOLLOWING
  	where(["id != :current_user_id and exists (
  		select 1 from followers
  		where followed_by = :current_user_id
  		and user_id = users.id)", {current_user_id: current_user_id}]).all
  	
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/followers_controller.rb
class FollowersController < ApplicationController

	def index
		render json: User.following(current_user.id)
	end

	def random
		render json: User.who_to_follow(current_user.id)
		
	end

	def unfollow
	  follower = Follower.find_by(
	    user_id: params[:user_id],
	    followed_by: current_user.id
	  )
	  follower.destroy

	  render json: follower
	end



	def create
		follower = Follower.create(user_id: params[:user_id],
		 						   followed_by: current_user.id)

		render json: follower
			
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	before_action :authenticate_user!
	
	def index
	end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
	before_action :authenticate_user!
  def index
  	@user = current_user
  end

  def update
  	current_user.update(user_params)
  	redirect_to root_path
  end

  private
  def user_params
  	params.require(:user).permit(:first_name, :last_name)
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
	def index
		render json: Tweet.stream_for(current_user.id) 
			
	end

	def create
		tweet = Tweet.create(body: params[:body], user_id:current_user.id)
		render json: tweet
		
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/followers_helper.rb
module FollowersHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/home/index.html.erb
<div id="react"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TwitterClone</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.3/css/materialize.min.css">

  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.3/js/materialize.min.js"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.6/moment.min.js"></script>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <%= csrf_meta_tags %>
</head>
<body>
<div class="right">
	<% if user_signed_in? %>
	Welcome 
	<%= link_to current_user.display_name, profile_path  %>,
	<%= link_to "logout", destroy_user_session_path, method: 'DELETE' %>
	<% else %>
	Please 
	<%= link_to "login", new_user_session_path %>
	or
	<%= link_to "signup", new_user_registration_path %>
	<% end %>
</div>


    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>


<%= yield %>

</body>
</html>